#!/bin/bash

set -e

echo "🚨 Production Runbook - AAP Exclusiva v3.0"
echo "=========================================="
echo ""
echo "Emergency Procedures:"
echo ""
echo "1. CHECK STATUS:"
echo "   kubectl get pods -n production"
echo "   kubectl get svc -n production"
echo ""
echo "2. SCALE UP/DOWN:"
echo "   kubectl scale deployment aap-backend --replicas=5 -n production"
echo ""
echo "3. VIEW LOGS:"
echo "   kubectl logs -f deployment/aap-backend -n production"
echo ""
echo "4. ROLLBACK:"
echo "   kubectl rollout undo deployment/aap-backend -n production"
echo ""
echo "5. RESTART PODS:"
echo "   kubectl delete pod <pod-name> -n production"
echo ""
echo "6. EXECUTE SHELL IN POD:"
echo "   kubectl exec -it <pod-name> -n production -- /bin/sh"
echo ""
echo "7. BACKUP DATABASE:"
echo "   kubectl exec -it postgres-0 -n production -- pg_dump -U postgres aap_db | gzip > backup.sql.gz"
echo ""
echo "8. PORT FORWARD:"
echo "   kubectl port-forward svc/aap-backend 8000:80 -n production"
echo ""
echo "9. VIEW METRICS:"
echo "   kubectl top nodes"
echo "   kubectl top pods -n production"
echo ""
echo "10. EMERGENCY: SCALE TO ZERO (drain all)"
echo "    kubectl scale deployment aap-backend --replicas=0 -n production"
